# fly.toml app configuration file generated for execlogdemo_dev on 2024-09-17T15:38:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'execlogdemo-dev'
primary_region = 'mad'

[build]
  dockerfile = './dev.Dockerfile'

[http_service]
  internal_port = 5173
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
